name: detect-defect-solar-cells
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy<=1.16.4
  - scipy
  - pandas
  - matplotlib
  - scikit-image
  - scikit-learn
  - jupyterlab
  - tqdm
  - pytorch=1.3.1
  - cudatoolkit=10.0
  - pip
  - pip:
      - torchvision==0.4.1
      - onnxruntime
